name: esm-ss-26 # Name needs to be changed in .github/workflows/update-pinned-env.yaml too
channels:
- conda-forge
dependencies:
- python>=3.13,<3.14
- pip

  # main packages
- numpy
- scipy
- pandas>=2
- pypsa>=1.1.2
- geopandas>=1
- xarray
- networkx
- yaml
- pyomo>=6.6
- netcdf4
- atlite>=0.5
- powerplantmatching>=0.8.1
- rasterio>=1.4.3
- pysheds
- pyarrow
- numba

  # interactive python
- ipython
- jupyterlab

  # reading particular file types
- tabula-py
- xlrd
- lxml
- pytables
- pyxlsb
- openpyxl
- libgdal-hdf5
- libgdal-netcdf
- cfgrib

  # geodata utilities
- shapely>2
- pyepsg
- cartopy>=0.22
- country_converter

  # plotting
- matplotlib>=3.9
- plotly
- geoviews>=1.10
- graphviz

  # publishing
- jupyter-book
- ghp-import
- pre-commit

- pip:
  - highspy>=1.13
